server:
  port: 8080

# tomcat文件传输限制
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 七牛云秘钥
oss:
  qiniu:
    accessKey: A_Oq5r4u1CxkfjqK76gvbzcisZKy58HS7aNJEpgX
    secretKey: K4ZS0TPpBH6cY9_mUhezpEMOEIcFZKJ5Fqk7P2e6
    bucketName: filetransferpractice
    bucketPath: http://rsxjnizx9.hn-bkt.clouddn.com/

# 消息内容
message:
  success: 操作成功
  fileNullError: 文件不能为空
  fileNameNullError: 文件名不能为空
  invalidFileNameError: 文件名应仅包含汉字、字母、数字、下划线和点号
  fileTypeError: 文件类型不匹配
  fileSizeExceededError: 文件大小过大
  deleteFalseError: 文件删除失败
  fileNotExistError: 目标文件不存在
  queryPageError: 页码错误

